"""This test the homepage"""

def test_request_main_menu_links(client):
    """This makes the index page"""
    response = client.get("/")
    assert response.status_code == 200
    assert b'<li class="nav-item"><a href="../templates/base_test.html" class="nav-link" aria-current="page">Home</a></li>' in response.data
    assert b'<li class="nav-item"><a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a></li>' in response.data
    assert b'<li class="nav-item"><a href="/app/simple_pages/templates/page2.html" class="nav-link">Docker</a></li>' in response.data
    assert b'<li class="nav-item"><a href="/app/simple_pages/templates/page3.html" class="nav-link">Python / Flask</a></li>' in response.data
    assert b'<li class="nav-item"><a href="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a></li>' in response.data

def test_request_index(client):
    """This makes the index page"""
    response = client.get("/base_test")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n\n        <style>\n    '
 b'        .bd-placeholder-img {\n        font-size: 1.125rem;\n        text-'
 b'anchor: middle;\n        -webkit-user-select: none;\n        -moz-user-sel'
 b'ect: none;\n        user-select: none;\n      }\n\n      @media (min-width: '
 b'768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n '
 b"       }\n      }\n        </style>\n\n        <title>This is Charles' Websi"
 b'te</title>\n  </head>\n  <body>\n    <main>\n\n        <div class="contai'
 b'ner">\n            <header class="d-flex flex-wrap justify-content-center'
 b' py-3 mb-4 border-bottom">\n              <a href="../templates/base_test'
 b'.html" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark te'
 b'xt-decoration-none">\n                <svg class="bi me-2" width="40" hei'
 b'ght="32"></svg>\n                <span class="fs-4">Charles\' Site</span>\n'
 b'              </a>\n\n              <ul class="nav nav-pills">\n           '
 b'     <li class="nav-item"><a href="../templates/base_test.html" class="nav-l'
 b'ink" aria-current="page">Home</a></li>\n                <li class="nav-it'
 b'em"><a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a'
 b'></li>\n                <li class="nav-item"><a href="/app/simple_pages/t'
 b'emplates/page2.html" class="nav-link">Docker</a></li>\n                <l'
 b'i class="nav-item"><a href="/app/simple_pages/templates/page3.html" class="n'
 b'av-link">Python / Flask</a></li>\n                <li class="nav-item"><a'
 b' href="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a><'
 b'/li>\n              </ul>\n            </header>\n        </div>\n\n    <'
 b'div id="myCarousel" class="carousel slide" data-bs-ride="carousel">\n    '
 b'<div class="carousel-indicators">\n      <button type="button" data-bs-ta'
 b'rget="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" a'
 b'ria-label="Slide 1"></button>\n      <button type="button" data-bs-target'
 b'="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>\n     '
 b' <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" ari'
 b'a-label="Slide 3"></button>\n        <button type="button" data-bs-target'
 b'="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>\n    <'
 b'/div>\n    <div class="carousel-inner">\n      <div class="carousel-item a'
 b'ctive">\n        <svg class="bd-placeholder-img" width="100%" height="100'
 b'%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio'
 b'="xMidYMid slice" focusable="false">\n          <rect width="100%" height'
 b'="100%" fill="#777"/></svg>\n\n        <div class="container">\n          <'
 b'div class="carousel-caption text-start">\n            <h1>Git</h1>\n      '
 b'      <p>Explanation of Branches, Merge, Commit, Tags, and Repositories.</p>'
 b'\n            <p><a class="btn btn-lg btn-primary" href="/app/simple_page'
 b's/templates/page1.html">Go to Page / Learn More</a></p>\n          </div>'
 b'\n        </div>\n      </div>\n      <div class="carousel-item">\n        <'
 b'svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.'
 b'w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" foc'
 b'usable="false"><rect width="100%" height="100%" fill="#777"/></svg>\n\n   '
 b'     <div class="container">\n          <div class="carousel-caption">\n  '
 b'          <h1>Docker</h1>\n            <p>Explanation of containers, imag'
 b'es, docker commands, etc.</p>\n            <p><a class="btn btn-lg btn-pr'
 b'imary" href="/app/simple_pages/templates/page2.html">Go to Page / Learn More'
 b'</a></p>\n          </div>\n        </div>\n      </div>\n      <div class="'
 b'carousel-item">\n        <svg class="bd-placeholder-img" width="100%" hei'
 b'ght="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAsp'
 b'ectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%"'
 b' fill="#777"/></svg>\n\n        <div class="container">\n          <div cla'
 b'ss="carousel-caption text-end">\n            <h1>Python / Flask</h1>\n    '
 b'        <p>Pytest, simple pages, and explanation of files.</p>\n         '
 b'   <p><a class="btn btn-lg btn-primary" href="/app/simple_pages/templates/pa'
 b'ge3.html">Go to Page / Learn More</a></p>\n          </div>\n        </div'
 b'>\n      </div>\n        <div class="carousel-item">\n        <svg class="b'
 b'd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/'
 b'svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="fals'
 b'e"><rect width="100%" height="100%" fill="#777"/></svg>\n\n        <div cl'
 b'ass="container">\n          <div class="carousel-caption">\n            <h'
 b'1>Continuous Integration / Deployment</h1>\n            <p>Explanation of'
 b' GitHub Actions, reviewing code, deployment of code.</p>\n            <p>'
 b'<a class="btn btn-lg btn-primary" href="/app/simple_pages/templates/page4.ht'
 b'ml">Go to Page / Learn More</a></p>\n          </div>\n        </div>\n    '
 b'  </div>\n\n    </div>\n    <button class="carousel-control-prev" type="but'
 b'ton" data-bs-target="#myCarousel" data-bs-slide="prev">\n      <span clas'
 b's="carousel-control-prev-icon" aria-hidden="true"></span>\n      <span cl'
 b'ass="visually-hidden">Previous</span>\n    </button>\n    <button class="c'
 b'arousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-sli'
 b'de="next">\n      <span class="carousel-control-next-icon" aria-hidden="t'
 b'rue"></span>\n      <span class="visually-hidden">Next</span>\n    </butto'
 b'n>\n  </div>\n\n    </main>\n    <!-- Option 1: Bootstrap Bundle with Popper'
 b' -->\n    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/'
 b'js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg'
 b'+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>\n  '
 b'</body>\n</html>') in response.data

def test_request_about(client):
    """This makes the index page"""
    response = client.get("/about")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n\n        <style>\n    '
 b'        .bd-placeholder-img {\n        font-size: 1.125rem;\n        text-'
 b'anchor: middle;\n        -webkit-user-select: none;\n        -moz-user-sel'
 b'ect: none;\n        user-select: none;\n      }\n\n      @media (min-width: '
 b'768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n '
 b"       }\n      }\n        </style>\n\n        <title>This is Charles' Websi"
 b'te</title>\n  </head>\n  <body>\n    <main>\n\n        <div class="contai'
 b'ner">\n            <header class="d-flex flex-wrap justify-content-center'
 b' py-3 mb-4 border-bottom">\n              <a href="../templates/base_test'
 b'.html" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark te'
 b'xt-decoration-none">\n                <svg class="bi me-2" width="40" hei'
 b'ght="32"></svg>\n                <span class="fs-4">Charles\' Site</span>\n'
 b'              </a>\n\n              <ul class="nav nav-pills">\n           '
 b'     <li class="nav-item"><a href="../templates/base_test.html" class="nav-l'
 b'ink" aria-current="page">Home</a></li>\n                <li class="nav-it'
 b'em"><a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a'
 b'></li>\n                <li class="nav-item"><a href="/app/simple_pages/t'
 b'emplates/page2.html" class="nav-link">Docker</a></li>\n                <l'
 b'i class="nav-item"><a href="/app/simple_pages/templates/page3.html" class="n'
 b'av-link">Python / Flask</a></li>\n                <li class="nav-item"><a'
 b' href="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a><'
 b'/li>\n              </ul>\n            </header>\n        </div>\n\n    <'
 b'div id="myCarousel" class="carousel slide" data-bs-ride="carousel">\n    '
 b'<div class="carousel-indicators">\n      <button type="button" data-bs-ta'
 b'rget="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" a'
 b'ria-label="Slide 1"></button>\n      <button type="button" data-bs-target'
 b'="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>\n     '
 b' <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" ari'
 b'a-label="Slide 3"></button>\n        <button type="button" data-bs-target'
 b'="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>\n    <'
 b'/div>\n    <div class="carousel-inner">\n      <div class="carousel-item a'
 b'ctive">\n        <svg class="bd-placeholder-img" width="100%" height="100'
 b'%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio'
 b'="xMidYMid slice" focusable="false">\n          <rect width="100%" height'
 b'="100%" fill="#777"/></svg>\n\n        <div class="container">\n          <'
 b'div class="carousel-caption text-start">\n            <h1>Git</h1>\n      '
 b'      <p>Explanation of Branches, Merge, Commit, Tags, and Repositories.</p>'
 b'\n            <p><a class="btn btn-lg btn-primary" href="/app/simple_page'
 b's/templates/page1.html">Go to Page / Learn More</a></p>\n          </div>'
 b'\n        </div>\n      </div>\n      <div class="carousel-item">\n        <'
 b'svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.'
 b'w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" foc'
 b'usable="false"><rect width="100%" height="100%" fill="#777"/></svg>\n\n   '
 b'     <div class="container">\n          <div class="carousel-caption">\n  '
 b'          <h1>Docker</h1>\n            <p>Explanation of containers, imag'
 b'es, docker commands, etc.</p>\n            <p><a class="btn btn-lg btn-pr'
 b'imary" href="/app/simple_pages/templates/page2.html">Go to Page / Learn More'
 b'</a></p>\n          </div>\n        </div>\n      </div>\n      <div class="'
 b'carousel-item">\n        <svg class="bd-placeholder-img" width="100%" hei'
 b'ght="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAsp'
 b'ectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%"'
 b' fill="#777"/></svg>\n\n        <div class="container">\n          <div cla'
 b'ss="carousel-caption text-end">\n            <h1>Python / Flask</h1>\n    '
 b'        <p>Pytest, simple pages, and explanation of files.</p>\n         '
 b'   <p><a class="btn btn-lg btn-primary" href="/app/simple_pages/templates/pa'
 b'ge3.html">Go to Page / Learn More</a></p>\n          </div>\n        </div'
 b'>\n      </div>\n        <div class="carousel-item">\n        <svg class="b'
 b'd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/'
 b'svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="fals'
 b'e"><rect width="100%" height="100%" fill="#777"/></svg>\n\n        <div cl'
 b'ass="container">\n          <div class="carousel-caption">\n            <h'
 b'1>Continuous Integration / Deployment</h1>\n            <p>Explanation of'
 b' GitHub Actions, reviewing code, deployment of code.</p>\n            <p>'
 b'<a class="btn btn-lg btn-primary" href="/app/simple_pages/templates/page4.ht'
 b'ml">Go to Page / Learn More</a></p>\n          </div>\n        </div>\n    '
 b'  </div>\n\n    </div>\n    <button class="carousel-control-prev" type="but'
 b'ton" data-bs-target="#myCarousel" data-bs-slide="prev">\n      <span clas'
 b's="carousel-control-prev-icon" aria-hidden="true"></span>\n      <span cl'
 b'ass="visually-hidden">Previous</span>\n    </button>\n    <button class="c'
 b'arousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-sli'
 b'de="next">\n      <span class="carousel-control-next-icon" aria-hidden="t'
 b'rue"></span>\n      <span class="visually-hidden">Next</span>\n    </butto'
 b'n>\n  </div>\n\n    </main>\n    <!-- Option 1: Bootstrap Bundle with Popper'
 b' -->\n    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/'
 b'js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg'
 b'+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>\n  '
 b'</body>\n</html>') in response.data

def test_request_page1(client):
    """This makes the index page"""
    response = client.get("/page1")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n        <link href="/'
 b'app/static/css/blog.css" rel="stylesheet">\n          <link href="https:/'
 b'/fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=sw'
 b'ap" rel="stylesheet">\n\n\n        <style>\n            .bd-placeholder-img '
 b'{\n        font-size: 1.125rem;\n        text-anchor: middle;\n        -web'
 b'kit-user-select: none;\n        -moz-user-select: none;\n        user-sele'
 b'ct: none;\n      }\n\n      @media (min-width: 768px) {\n        .bd-placeho'
 b'lder-img-lg {\n          font-size: 3.5rem;\n        }\n      }\n        </s'
 b"tyle>\n\n        <title>This is Charles' Website</title>\n  </head>\n  <body"
 b'>\n    <main>\n\n        <div class="container">\n            <header class='
 b'"d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">\n     '
 b'         <a href="../templates/base_test.html" class="d-flex align-items-cen'
 b'ter mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">\n           '
 b'     <svg class="bi me-2" width="40" height="32"></svg>\n                '
 b'<span class="fs-4">Charles\' Site</span>\n              </a>\n\n            '
 b'  <ul class="nav nav-pills">\n                <li class="nav-item"><a hre'
 b'f="base_test.html" class="nav-link" aria-current="page">Home</a></li>\n  '
 b'              <li class="nav-item"><a href="page1.html" class="nav-link">Git'
 b'</a></li>\n                <li class="nav-item"><a href="page2.html" clas'
 b's="nav-link">Docker</a></li>\n                <li class="nav-item"><a hre'
 b'f="page3.html" class="nav-link">Python / Flask</a></li>\n                '
 b'<li class="nav-item"><a href="page4.html" class="nav-link">CI / CD</a></'
 b'li>\n              </ul>\n            </header>\n        </div>\n\n      '
 b'  <div class="row g-5">\n    <div class="col-md-8">\n      <h3 class="pb-4'
 b' mb-4 fst-italic border-bottom">\n        Git\n      </h3>\n\n      <article'
 b' class="blog-post">\n        <h2 class="blog-post-title">Explanations</h2'
 b'>\n\n        <dl>\n          <dt>Branches</dt>\n          <dd>Branches in Gi'
 b't are ways that devlopers can test and develop\n          code without af'
 b'fecting the main part of the project.</dd>\n          <dt>Merge</dt>\n    '
 b'      <dd>Merging in terms of Git is a way of assimilating branches\n    '
 b"      into a single branch, adding the target branch's code to the curre"
 b"nt\n          branch's.</dd>\n          <dt>Commit</dt>\n          <dd>One "
 b"can think of Commiting in git as saving, setting a 'save point'\n        "
 b'  of sorts allowing a user to go back to this set of code if they\n      '
 b'    run into any bugs or want to change somthing.</dd>\n            <dt>T'
 b'ags</dt>\n            <dd>Tags in Git can be seen as more specific branch'
 b'es. While branches\n            can be changed, Tags cannot.</dd>\n       '
 b'     <dt>Repositories</dt>\n            <dd>Repositories can be seen as f'
 b'olders. They track all changes made to\n            projects, letting you'
 b' look back at the history of your project.</dd>\n        </dl>\n\n      </a'
 b'rticle>\n\n\n    </div>\n\n      </div>\n    </div>\n  </div>\n\n    </di'
 b'v>\n\n\n  </div>\n\n    </main>\n    <!-- Option 1: Bootstrap Bundle with '
 b'Popper -->\n    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3'
 b'/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1w'
 b'XgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></scri'
 b'pt>\n  </body>\n</html>') in response.data

def test_request_page2(client):
    """This makes the index page"""
    response = client.get("/page2")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n\n        <style>\n    '
 b'        .bd-placeholder-img {\n        font-size: 1.125rem;\n        text-'
 b'anchor: middle;\n        -webkit-user-select: none;\n        -moz-user-sel'
 b'ect: none;\n        user-select: none;\n      }\n\n      @media (min-width: '
 b'768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n '
 b"       }\n      }\n        </style>\n\n        <title>This is Charles' Websi"
 b'te</title>\n  </head>\n  <body>\n    <main>\n\n        <div class="contai'
 b'ner">\n            <header class="d-flex flex-wrap justify-content-center'
 b' py-3 mb-4 border-bottom">\n              <a href="javascript:history.bac'
 b'k()" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text'
 b'-decoration-none">\n                <svg class="bi me-2" width="40" heigh'
 b't="32"></svg>\n                <span class="fs-4">Charles\' Site</span>\n  '
 b'            </a>\n\n              <ul class="nav nav-pills">\n             '
 b'   <li class="nav-item"><a href="javascript:history.back()" class="nav-link"'
 b' aria-current="page">Home</a></li>\n                <li class="nav-item">'
 b'<a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a></l'
 b'i>\n                <li class="nav-item"><a href="/app/simple_pages/templ'
 b'ates/page2.html" class="nav-link">Docker</a></li>\n                <li cl'
 b'ass="nav-item"><a href="/app/simple_pages/templates/page3.html" class="nav-l'
 b'ink">Python / Flask</a></li>\n                <li class="nav-item"><a hre'
 b'f="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a></li>'
 b'\n              </ul>\n            </header>\n        </div>\n\n        <'
 b'div class="row g-5">\n    <div class="col-md-8">\n      <h3 class="pb-4 mb'
 b'-4 fst-italic border-bottom">\n        Docker\n      </h3>\n\n      <article'
 b' class="blog-post">\n        <h2 class="blog-post-title">Explanations</h2'
 b'>\n\n        <dl>\n          <dt>Containers</dt>\n          <dd>A Docker con'
 b'tainer is an executable pack of software with\n          added dependenci'
 b'es that allow it to be run in any environment.</dd>\n          <dt>Images'
 b'</dt>\n          <dd>Docker Images are files that are used to execute cod'
 b'e found\n          in a Docker Container.</dd>\n          <dt>Link to Proj'
 b'ect Repository</dt>\n          <dd><a href="https://hub.docker.com/layers'
 b'/cle4/docker_flask/master/images/sha256-ab1eae2fe3fcf0cf1b78f9aa001209bccb50'
 b'54350f1e4c63a9eb7d644a20971c?context=explore">\n          Click Here\n    '
 b'      </a>\n          </dd>\n            <dt>Docker Commands Known</dt>\n  '
 b'          <dd>docker run- | creates a container from an image and starts the'
 b' container with the commands given.</dd>\n            <dd>docker build- |'
 b' creates an image from the code given.</dd>\n            <dd>docker image'
 b's- | checks the current images on our local machine. </dd>\n            <'
 b'dd>docker ps- | this lists all of the running containers on the local machin'
 b'e.</dd>\n            <dd>docker stop- | this stops any container specifie'
 b'd with their id/name. </dd>\n            <dd>docker restart- | this stops'
 b' and starts the specified container. </dd>\n            <dd>docker rm- | '
 b'this removes the specified container.</dd>\n            <dd>docker pull- '
 b'| this pulls images from the docker repository.</dd>\n            <dt>Exp'
 b'lanation of starting Project and Accessing Container</dt>\n            <d'
 b'd>In order to start the Project, one first needs the code. To get the code, '
 b'you can use docker pull cle4/docker_flask:master\n            to pull the'
 b' needed code. once you have the code, you can use docker run -p 80:80 cle4/d'
 b'ocker_flask to construct a container\n                from the image, and'
 b' set it to the localhost port, allowing you to see what the container builds'
 b'.</dd>\n        </dl>\n\n      </article>\n\n\n    </div>\n\n      </div'
 b'>\n\n    </main>\n    <!-- Option 1: Bootstrap Bundle with Popper -->\n    <'
 b'script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.b'
 b'undle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sE'
 b'NBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>\n  </body>\n</html>') in response.data

def test_request_page3(client):
    """This makes the index page"""
    response = client.get("/page3")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n\n        <style>\n    '
 b'        .bd-placeholder-img {\n        font-size: 1.125rem;\n        text-'
 b'anchor: middle;\n        -webkit-user-select: none;\n        -moz-user-sel'
 b'ect: none;\n        user-select: none;\n      }\n\n      @media (min-width: '
 b'768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n '
 b"       }\n      }\n        </style>\n\n        <title>This is Charles' Websi"
 b'te</title>\n  </head>\n  <body>\n    <main>\n\n        <div class="contai'
 b'ner">\n            <header class="d-flex flex-wrap justify-content-center'
 b' py-3 mb-4 border-bottom">\n              <a href="javascript:history.bac'
 b'k()" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text'
 b'-decoration-none">\n                <svg class="bi me-2" width="40" heigh'
 b't="32"></svg>\n                <span class="fs-4">Charles\' Site</span>\n  '
 b'            </a>\n\n              <ul class="nav nav-pills">\n             '
 b'   <li class="nav-item"><a href="javascript:history.back()" class="nav-link"'
 b' aria-current="page">Home</a></li>\n                <li class="nav-item">'
 b'<a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a></l'
 b'i>\n                <li class="nav-item"><a href="/app/simple_pages/templ'
 b'ates/page2.html" class="nav-link">Docker</a></li>\n                <li cl'
 b'ass="nav-item"><a href="/app/simple_pages/templates/page3.html" class="nav-l'
 b'ink">Python / Flask</a></li>\n                <li class="nav-item"><a hre'
 b'f="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a></li>'
 b'\n              </ul>\n            </header>\n        </div>\n    <div class'
 b'="row g-5">\n    <div class="col-md-8">\n      <h3 class="pb-4 mb-4 fst-it'
 b'alic border-bottom">\n        Docker\n      </h3>\n\n      <article class="b'
 b'log-post">\n        <h2 class="blog-post-title">Explanations</h2>\n\n      '
 b'  <dl>\n          <dt>Testing with pytest; examples with code</dt>\n      '
 b'    <dd>pytest testing allowed for us to make sure the pages were loading pr'
 b'operly and that there were no problems.</dd>\n            <dd>Some exampl'
 b'e code of what was done being:</dd>\n            <dd>def test_request_abo'
 b'ut(client):\n            <dd>"""This makes the about page"""</dd>\n       '
 b'     <dd>response = client.get("/about")</dd>\n            <dd>assert res'
 b'ponse.status_code == 200</dd>\n            <dd>assert b"About Page" in re'
 b'sponse.data</dd>\n            </dd>\n          <dt>Simple Pages creation &'
 b' testing</dt>\n            <dd>simple pages was created by pulling the bl'
 b'ueprint formula from flask, which when used in tandem with the html pages cr'
 b'eated in the templates folder, and supporting css and images\n           '
 b' in the static folder allowed for me to check that everything was working as'
 b' intended when ran.</dd>\n\n          <dt>Project Outline</dt>\n           '
 b' <dd>\n                <ul>\n                <li> dockflask <-- root of th'
 b'e project</li>\n                    <ul>\n                        <li>.git'
 b'hub <-- contains the workflows folder for GitHub to use</li>\n           '
 b'             <ul>\n                            <li>workflows <-- integrat'
 b'ion for github workflows to run tests on every push to GitHub</li>\n     '
 b'                   </ul>\n                    </ul>\n                    <'
 b'ul>\n                        <li>app <-- contains html and css files as w'
 b'ell as simple_pages to run the application.</li>\n                       '
 b' <ul>\n                            <li>simple_pages <-- contains the html'
 b' files and tests for them. </li><ul><li>templates <-- contains all html file'
 b's.</li></ul>\n                            <li>static <-- contains the css'
 b' and image files required for the html files.</li><ul><li>css <-- contains a'
 b'll css files for the project</li></ul><ul><li>images <-- contains all images'
 b' required for the project</li></ul>\n                        </ul>\n      '
 b'              </ul>\n                    <ul>\n                        <li'
 b'>calculator <-- contains calculation and operation files for the calculator.'
 b'</li>\n                        <ul>\n                            <li>calcu'
 b'lation <-- contains the source code to run addition, subtracton and multipli'
 b'cation constructor methods.</li>\n                            <li>operati'
 b'ons <-- contains the static methods which call on the constructor methods to'
 b' output desired results. </li>\n                        </ul>\n           '
 b'         </ul>\n                    <ul>\n                        <li>.tes'
 b'ts <-- contains all the test python files from calculator to homepage tests,'
 b' which ensure everything is working as intended. </li>\n                 '
 b'   </ul>\n                    <ul>\n                        <li>.dockerign'
 b'ore <-- tells Docker what command to ignore within the code.</li>\n      '
 b'                  <li>.gitignore <-- tells git what commands to ignore in th'
 b'e code.</li>\n                        <li>docker-compose.yml <-- contains'
 b' the settings to develop on your local machine</li>\n                    '
 b'    <li>Dockerfile <-- contains all the commands required to build images.</'
 b'li>\n                        <li>heroku.yml <-- allows one to construct d'
 b'ocker images on heroku.</li>\n                        <li>pytest.ini <-- '
 b'reroutes testpaths to tests and filterwarnings to ignore</li>\n          '
 b'              <li>readme.md <-- comments and instructions to any viewers of '
 b'the repository / file.</li>\n                        <li>requirements.txt'
 b' <-- tells the developer what requirements are needed to work on the code.</'
 b'li>\n                    </ul>\n                </ul>\n                <ul>'
 b'\n\n                </ul>\n            </dd>\n\n        </dl>\n\n      </ar'
 b'ticle>\n\n\n    </div>\n\n      </div>\n\n    </main>\n    <!-- Option 1: Bo'
 b'otstrap Bundle with Popper -->\n    <script src="https://cdn.jsdelivr.net'
 b'/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7S'
 b'k0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="a'
 b'nonymous"></script>\n  </body>\n</html>') in response.data

def test_request_page4(client):
    """This makes the index page"""
    response = client.get("/page4")
    assert response.status_code == 200
    assert (b'<!doctype html>\n<html lang="en">\n  <head>\n    <!-- Required meta tags --'
 b'>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=de'
 b'vice-width, initial-scale=1">\n\n    <!-- Bootstrap CSS -->\n    <link href'
 b'="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" r'
 b'el="stylesheet"\n          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6au'
 b'U8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">\n\n\n       '
 b' <link rel="stylesheet" href="/static/css/style.css"/>\n        <link rel'
 b'="stylesheet" href="/app/static/css/carousel.css">\n\n        <style>\n    '
 b'        .bd-placeholder-img {\n        font-size: 1.125rem;\n        text-'
 b'anchor: middle;\n        -webkit-user-select: none;\n        -moz-user-sel'
 b'ect: none;\n        user-select: none;\n      }\n\n      @media (min-width: '
 b'768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n '
 b"       }\n      }\n        </style>\n\n        <title>This is Charles' Websi"
 b'te</title>\n  </head>\n  <body>\n    <main>\n\n        <div class="contai'
 b'ner">\n            <header class="d-flex flex-wrap justify-content-center'
 b' py-3 mb-4 border-bottom">\n              <a href="javascript:history.bac'
 b'k()" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text'
 b'-decoration-none">\n                <svg class="bi me-2" width="40" heigh'
 b't="32"></svg>\n                <span class="fs-4">Charles\' Site</span>\n  '
 b'            </a>\n\n              <ul class="nav nav-pills">\n             '
 b'   <li class="nav-item"><a href="javascript:history.back()" class="nav-link"'
 b' aria-current="page">Home</a></li>\n                <li class="nav-item">'
 b'<a href="/app/simple_pages/templates/page1.html" class="nav-link">Git</a></l'
 b'i>\n                <li class="nav-item"><a href="/app/simple_pages/templ'
 b'ates/page2.html" class="nav-link">Docker</a></li>\n                <li cl'
 b'ass="nav-item"><a href="/app/simple_pages/templates/page3.html" class="nav-l'
 b'ink">Python / Flask</a></li>\n                <li class="nav-item"><a hre'
 b'f="/app/simple_pages/templates/page4.html" class="nav-link">CI / CD</a></li>'
 b'\n              </ul>\n            </header>\n        </div>\n     <div clas'
 b's="row g-5">\n    <div class="col-md-8">\n      <h3 class="pb-4 mb-4 fst-i'
 b'talic border-bottom">\n        Continuous Integration / Deployment\n      '
 b'</h3>\n\n      <article class="blog-post">\n        <h2 class="blog-post-ti'
 b'tle">Explanations</h2>\n\n        <dl>\n          <dt></dt>\n          <dd><'
 b'/dd>\n          <dt></dt>\n          <dd></dd>\n        </dl>\n\n      </'
 b'article>\n\n\n    </div>\n\n      </div>\n\n    </main>\n    <!-- Option 1: '
 b'Bootstrap Bundle with Popper -->\n    <script src="https://cdn.jsdelivr.n'
 b'et/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka'
 b'7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin='
 b'"anonymous"></script>\n  </body>\n</html>') in response.data

def test_request_page_not_found(client):
    """This makes the index page"""
    response = client.get("/page5")
    assert response.status_code == 404